// Auto-generated by scripts/generate-build-id.mjs — do not edit manually
export const VERSION = "0.1.0";
export const BUILD_ID = 11;
export const BUILD_TIME = "2026-05-19T09:41:36.340Z";
export const BUILD_LABEL = "0.1.0+b11";
